// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCASxr3DPLLaAQtgCNpvD2yuaSAp_UNBig',
    appId: '1:1024877792349:web:12c81765bb26d00fff51b4',
    messagingSenderId: '1024877792349',
    projectId: 'yemek-vadisi',
    authDomain: 'yemek-vadisi.firebaseapp.com',
    storageBucket: 'yemek-vadisi.firebasestorage.app',
    measurementId: 'G-54MKHFYDEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumm-FeRoHSETflaWKXWOHHWjE4kDdBuE',
    appId: '1:1024877792349:android:e67fd28655b3c120ff51b4',
    messagingSenderId: '1024877792349',
    projectId: 'yemek-vadisi',
    storageBucket: 'yemek-vadisi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUh0J-qwH655hfwYEN8urzPqsYST2De40',
    appId: '1:1024877792349:ios:15b3b48724f9c781ff51b4',
    messagingSenderId: '1024877792349',
    projectId: 'yemek-vadisi',
    storageBucket: 'yemek-vadisi.firebasestorage.app',
    iosBundleId: 'com.example.yemekvadisii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUh0J-qwH655hfwYEN8urzPqsYST2De40',
    appId: '1:1024877792349:ios:15b3b48724f9c781ff51b4',
    messagingSenderId: '1024877792349',
    projectId: 'yemek-vadisi',
    storageBucket: 'yemek-vadisi.firebasestorage.app',
    iosBundleId: 'com.example.yemekvadisii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCASxr3DPLLaAQtgCNpvD2yuaSAp_UNBig',
    appId: '1:1024877792349:web:520dc22957903e4bff51b4',
    messagingSenderId: '1024877792349',
    projectId: 'yemek-vadisi',
    authDomain: 'yemek-vadisi.firebaseapp.com',
    storageBucket: 'yemek-vadisi.firebasestorage.app',
    measurementId: 'G-L4V2HN2QL2',
  );
}
